#!/usr/bin/env bash
#
# Provisions a fresh cloud instance to run SERA.toolkit publicly.
#
# Written against Oracle Cloud's always-free Ampere (arm64) instance but not specific to
# it: it works on any Ubuntu or Oracle Linux host with a public IP. It installs Docker,
# opens the instance firewall, writes a production .env, and starts the stack behind Caddy
# with a real Let's Encrypt certificate.
#
#   curl -fsSL https://raw.githubusercontent.com/seraphicidal/sera-toolkit/main/deploy/provision.sh | bash
#
# or, from a checkout:  sudo bash deploy/provision.sh
#
# Safe to re-run: every step checks before acting.

set -euo pipefail

REPO="${SERA_REPO:-https://github.com/seraphicidal/sera-toolkit.git}"
INSTALL_DIR="${SERA_DIR:-/opt/sera}"
COMPOSE_FILE="deploy/docker-compose.oracle.yml"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m !  %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m !! %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run with sudo: sudo bash deploy/provision.sh"

# ---------------------------------------------------------------------------
# Packages
# ---------------------------------------------------------------------------

if command -v apt-get >/dev/null 2>&1; then
  PKG=apt
elif command -v dnf >/dev/null 2>&1; then
  PKG=dnf
else
  die "unsupported distribution: need apt or dnf"
fi

log "Installing Docker"
if ! command -v docker >/dev/null 2>&1; then
  # Docker's own convenience script handles arm64 and both distributions, and pins to the
  # official repository rather than whatever the distro happens to ship.
  curl -fsSL --retry 5 --retry-all-errors --retry-delay 3 --connect-timeout 20 https://get.docker.com | sh
else
  echo "Docker already present: $(docker --version)"
fi

docker compose version >/dev/null 2>&1 || die "the docker compose plugin is missing"

systemctl enable --now docker

# ---------------------------------------------------------------------------
# Instance firewall
# ---------------------------------------------------------------------------
#
# Cloud images ship with everything but SSH closed. This is separate from the cloud
# provider's own network rules — on Oracle you must ALSO add ingress rules for 80 and 443
# to the subnet's security list, or the packets never reach this machine.

log "Opening ports 80 and 443 on the instance"
if command -v firewall-cmd >/dev/null 2>&1 && systemctl is-active --quiet firewalld; then
  firewall-cmd --permanent --add-service=http
  firewall-cmd --permanent --add-service=https
  firewall-cmd --reload
  echo "firewalld updated"
elif command -v iptables >/dev/null 2>&1; then
  for port in 80 443; do
    if ! iptables -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null; then
      # Inserted at the top: the default rule set ends in a REJECT that would otherwise
      # match first.
      iptables -I INPUT 1 -p tcp --dport "$port" -m conntrack --ctstate NEW -j ACCEPT
      echo "iptables: opened $port"
    fi
  done
  if [ "$PKG" = apt ]; then
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq iptables-persistent >/dev/null 2>&1 || true
    netfilter-persistent save >/dev/null 2>&1 || warn "could not persist iptables rules"
  fi
else
  warn "no firewall tool found; assuming ports are already open"
fi

# ---------------------------------------------------------------------------
# Source
# ---------------------------------------------------------------------------

log "Fetching SERA.toolkit"
if [ -d "$INSTALL_DIR/.git" ]; then
  git -C "$INSTALL_DIR" pull --ff-only
else
  command -v git >/dev/null 2>&1 || { [ "$PKG" = apt ] && apt-get install -y -qq git || dnf install -y -q git; }
  git clone --depth 1 "$REPO" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

if [ ! -f .env ]; then
  log "Writing .env"

  # The instance's own public address. sslip.io resolves 1-2-3-4.sslip.io to 1.2.3.4
  # with no account and no registration, which is enough for Let's Encrypt to issue —
  # so a public HTTPS deployment needs no domain purchase.
  PUBLIC_IP="${SERA_PUBLIC_IP:-$(curl -fsS --max-time 10 https://api.ipify.org || true)}"
  [ -n "$PUBLIC_IP" ] || die "could not determine the public IP; set SERA_PUBLIC_IP and re-run"
  DOMAIN="${SERA_DOMAIN:-${PUBLIC_IP//./-}.sslip.io}"

  SECRET="$(openssl rand -hex 32)"

  cat > .env <<EOF
# Generated by deploy/provision.sh — do not commit.
SERA_SECRET=${SECRET}
SERA_DOMAIN=${DOMAIN}
SERA_TLS_EMAIL=${SERA_TLS_EMAIL:-}

SERA_RETENTION_SECONDS=1800
SERA_MAX_FILESIZE_BYTES=2147483648
SERA_MAX_DURATION_SECONDS=10800
SERA_WORKER_CONCURRENCY=2
LOG_LEVEL=info
EOF
  chmod 600 .env
  echo "domain: ${DOMAIN}"
else
  echo ".env already exists; leaving it alone"
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a

# ---------------------------------------------------------------------------
# Launch
# ---------------------------------------------------------------------------

log "Pulling images"
docker compose -f "$COMPOSE_FILE" pull

log "Starting the stack"
docker compose -f "$COMPOSE_FILE" up -d --remove-orphans

log "Waiting for the API to report healthy"
for _ in $(seq 1 60); do
  if docker compose -f "$COMPOSE_FILE" exec -T api \
      node -e "fetch('http://127.0.0.1:4000/health').then(r=>r.json()).then(j=>process.exit(j.status==='ok'?0:1)).catch(()=>process.exit(1))" \
      >/dev/null 2>&1; then
    break
  fi
  sleep 3
done

docker compose -f "$COMPOSE_FILE" ps

cat <<EOF

  SERA.toolkit is starting.

    https://${SERA_DOMAIN}

  Caddy needs a minute to obtain its certificate on the first run. If the site does not
  answer:

    1. Check the cloud firewall. On Oracle this is separate from the instance firewall:
       Networking > Virtual Cloud Networks > your VCN > Security Lists > add ingress
       rules for TCP 80 and 443 from 0.0.0.0/0.
    2. docker compose -f ${COMPOSE_FILE} logs caddy
    3. docker compose -f ${COMPOSE_FILE} logs api

  Useful afterwards:

    docker compose -f ${COMPOSE_FILE} ps
    docker compose -f ${COMPOSE_FILE} logs -f worker
    docker compose -f ${COMPOSE_FILE} pull && docker compose -f ${COMPOSE_FILE} up -d   # update

EOF
