#!/usr/bin/env node

import { spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LOCAL_ONLY = process.argv.includes('--local');

const API_PORT = 4000;
const WEB_PORT = 3200;

function loadOrCreateSecret() {
  const path = join(ROOT, '.env.production.local');
  if (existsSync(path)) {
    const match = /^SERA_SECRET=(.+)$/m.exec(readFileSync(path, 'utf8'));
    if (match?.[1]) return match[1].trim();
  }
  const secret = randomBytes(32).toString('hex');
  writeFileSync(
    path,
    [
      '# Generated by scripts/serve-public.mjs. Ignored by git — do not commit.',
      `SERA_SECRET=${secret}`,
      '',
    ].join('\n'),
  );
  console.log(`[sera] generated a signing secret in .env.production.local`);
  return secret;
}

function productionEnv(secret) {
  return {
    ...process.env,
    NODE_ENV: 'production',
    SERA_SECRET: secret,

    SERA_HOST: '127.0.0.1',
    SERA_PORT: String(API_PORT),

    SERA_DATA_DIR: join(ROOT, '.data', 'production'),

    SERA_QUEUE_DRIVER: 'memory',
    SERA_WORKER_CONCURRENCY: '2',

    SERA_MAX_FILESIZE_BYTES: String(2 * 1024 * 1024 * 1024),
    SERA_MAX_DURATION_SECONDS: String(3 * 60 * 60),
    SERA_MAX_ITEMS_PER_JOB: '25',
    SERA_JOB_TIMEOUT_SECONDS: '1200',
    SERA_MAX_QUEUE_DEPTH: '50',

    SERA_RETENTION_SECONDS: '900',
    SERA_REAP_INTERVAL_SECONDS: '60',

    SERA_RATE_LIMIT_RESOLVE_PER_MINUTE: '20',
    SERA_RATE_LIMIT_JOBS_PER_MINUTE: '8',
    SERA_MAX_CONCURRENT_JOBS_PER_CLIENT: '2',

    SERA_TRUST_PROXY: 'true',

    LOG_LEVEL: 'info',
  };
}

const children = new Set();
let shuttingDown = false;
let publicUrl;

const MAX_RESTARTS = 5;
const RESTART_WINDOW_MS = 60_000;

function supervise(label, command, argsFor, envFor, colour, onLine) {
  const prefix = `\u001b[${colour}m${label.padEnd(7)}\u001b[0m │ `;
  const crashes = [];

  const launch = () => {
    if (shuttingDown) return;

    const child = spawn(command, argsFor(), {
      cwd: ROOT,
      env: envFor(),
      stdio: ['ignore', 'pipe', 'pipe'],
      shell: false,
      windowsHide: true,
    });
    children.add(child);

    const relay = (stream) => {
      let buffer = '';
      stream.on('data', (chunk) => {
        buffer += chunk.toString();
        const lines = buffer.split('\n');
        buffer = lines.pop() ?? '';
        for (const line of lines) {
          onLine?.(line);
          process.stdout.write(`${prefix}${line}\n`);
        }
      });
    };
    relay(child.stdout);
    relay(child.stderr);

    child.on('close', (code) => {
      children.delete(child);
      if (shuttingDown) return;

      const now = Date.now();
      crashes.push(now);
      while (crashes.length && now - crashes[0] > RESTART_WINDOW_MS) crashes.shift();

      if (crashes.length > MAX_RESTARTS) {
        process.stdout.write(
          `${prefix}crashed ${crashes.length} times in a minute — not restarting\n`,
        );
        shutdown(code ?? 1);
        return;
      }

      const delay = Math.min(1000 * 2 ** (crashes.length - 1), 15_000);
      process.stdout.write(`${prefix}exited (${code}); restarting in ${delay / 1000}s\n`);
      setTimeout(launch, delay).unref();
    });
  };

  launch();
}

function shutdown(code = 0) {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log('\n[sera] shutting down…');
  for (const child of children) child.kill();
  setTimeout(() => process.exit(code), 500).unref();
}

process.on('SIGINT', () => shutdown(0));
process.on('SIGTERM', () => shutdown(0));

function prepareStandalone() {
  const built = join(ROOT, 'apps', 'web', '.next');
  const source = join(built, 'standalone');
  if (!existsSync(join(source, 'apps', 'web', 'server.js'))) {
    console.error('[sera] no production build found. Run: npm run build');
    process.exit(1);
  }

  const runDir = join(ROOT, '.data', 'run', 'web');
  rmSync(runDir, { recursive: true, force: true });
  mkdirSync(runDir, { recursive: true });
  cpSync(source, runDir, { recursive: true });

  cpSync(join(built, 'static'), join(runDir, 'apps', 'web', '.next', 'static'), {
    recursive: true,
  });
  cpSync(join(ROOT, 'apps', 'web', 'public'), join(runDir, 'apps', 'web', 'public'), {
    recursive: true,
  });

  return join(runDir, 'apps', 'web', 'server.js');
}

const secret = loadOrCreateSecret();
const env = productionEnv(secret);
const serverEntry = prepareStandalone();

console.log('[sera] starting production API on 127.0.0.1:' + API_PORT);
supervise(
  'api',
  process.execPath,
  () => [join(ROOT, 'apps', 'api', 'dist', 'index.js')],
  () => env,
  '32',
);

console.log('[sera] starting production web on 127.0.0.1:' + WEB_PORT);
supervise(
  'web',
  process.execPath,
  () => [serverEntry],
  () => ({
    ...env,
    PORT: String(WEB_PORT),
    HOSTNAME: '127.0.0.1',
    SERA_API_URL: `http://127.0.0.1:${API_PORT}`,
  }),
  '35',
);

if (!LOCAL_ONLY) {
  const cloudflared = join(
    ROOT,
    '.tools',
    process.platform === 'win32' ? 'cloudflared.exe' : 'cloudflared',
  );
  if (!existsSync(cloudflared)) {
    console.error('[sera] cloudflared not found in .tools/. Serving locally only.');
  } else {
    setTimeout(() => {
      if (shuttingDown) return;
      console.log('[sera] opening a public tunnel…');
      supervise(
        'tunnel',
        cloudflared,
        () => ['tunnel', '--no-autoupdate', '--url', `http://127.0.0.1:${WEB_PORT}`],
        () => process.env,
        '36',
        (line) => {
          const match = /(https:\/\/[a-z0-9-]+\.trycloudflare\.com)/i.exec(line);
          if (match?.[1] && !publicUrl) {
            publicUrl = match[1];
            writeFileSync(join(ROOT, '.data', 'public-url.txt'), publicUrl);
            console.log(`\n  ┌${'─'.repeat(60)}┐`);
            console.log(`  │  SERA.toolkit is live at:`.padEnd(61) + '│');
            console.log(`  │  ${publicUrl}`.padEnd(61) + '│');
            console.log(`  └${'─'.repeat(60)}┘\n`);
          }
        },
      );
    }, 3000);
  }
}
